vich_uploader:
    db_driver: orm

    mappings:
        protocole_pdfs:
            uri_prefix: /uploads/protocoles
            upload_destination: '%kernel.project_dir%/public/uploads/protocoles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
